# Eğitilmiş LSTM arıza modellerini düz float dizilerinden oluşan bir C++ başlık dosyasına aktarır.
import sys
from pathlib import Path

import joblib
import numpy as np
from tensorflow import keras

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from flight_data import FEATURES


def cpp_array(name, values):
    values = np.asarray(values, dtype=np.float32).flatten()
    body = ", ".join(f"{v:.9g}f" for v in values)
    return f"inline constexpr float {name}[{len(values)}] = {{{body}}};"


def export_model(prefix, cpp_name):
    meta = joblib.load(f"models/{prefix}_meta.joblib")
    scaler = joblib.load(f"models/{prefix}_scaler.joblib")
    model = keras.models.load_model(f"models/{prefix}_model.keras")
    kernel, recurrent_kernel, bias, dense1_kernel, dense1_bias, dense2_kernel, dense2_bias = model.get_weights()

    units = recurrent_kernel.shape[0]
    n_features = kernel.shape[0]
    dense1_units = dense1_kernel.shape[1]
    n_classes = dense2_kernel.shape[1]
    assert kernel.shape == (n_features, 4 * units)
    expected_features = list(FEATURES) + [f"{feature}_delta" for feature in FEATURES]
    assert list(meta["features"]) == expected_features, (
        "feature order changed - update main_replay.cpp's row layout to match"
    )

    lines = [
        f"// Auto-generated by cpp/export_weights.py from {prefix}_model.keras - do not hand-edit.",
        "#pragma once",
        "",
        f"namespace {cpp_name} {{",
        "",
        f"constexpr int WINDOW_SIZE = {meta['window_size']};",
        f"constexpr int N_FEATURES = {n_features};",
        f"constexpr int LSTM_UNITS = {units};",
        f"constexpr int DENSE1_UNITS = {dense1_units};",
        f"constexpr int N_CLASSES = {n_classes};",
        f"constexpr int HORIZON = {meta.get('horizon', 0)};",
        "",
        "// LSTM gate order along the last axis: input, forget, cell, output (Keras convention).",
        cpp_array("lstm_kernel", kernel),
        cpp_array("lstm_recurrent_kernel", recurrent_kernel),
        cpp_array("lstm_bias", bias),
        cpp_array("dense1_kernel", dense1_kernel),
        cpp_array("dense1_bias", dense1_bias),
        cpp_array("dense2_kernel", dense2_kernel),
        cpp_array("dense2_bias", dense2_bias),
        cpp_array("scaler_mean", scaler.mean_),
        cpp_array("scaler_scale", scaler.scale_),
        "",
        "inline const char* CLASS_NAMES[N_CLASSES] = {"
        + ", ".join(f'"{c}"' for c in meta["classes"]) + "};",
        "",
        f"}}  // namespace {cpp_name}",
        "",
    ]
    out_path = Path(__file__).resolve().parent / f"weights_{cpp_name}.h"
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path} ({len(kernel.flatten()) + len(recurrent_kernel.flatten())} LSTM weights, "
          f"classes={list(meta['classes'])}, horizon={meta.get('horizon', 0)})")


if __name__ == "__main__":
    import os
    os.chdir(Path(__file__).resolve().parent.parent)
    export_model("fault", "current_fault")
    export_model("fault_next", "next_fault")
